In [1]:
import numpy as np
import pandas as pd
from numpy.matrixlib.defmatrix import matrix

In [30]:
arr = np.array([26, 7, 19, 27, 12, 29])
arr2 = np.arange(10)
print(arr2)
print(arr.size)

[0 1 2 3 4 5 6 7 8 9]
6


In [24]:
a = np.empty([1, 10], dtype=int)
b = np.zeros([1, 10], dtype=int)
print(a)
print(b)

[[4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408]]
[[0 0 0 0 0 0 0 0 0 0]]


In [35]:
a = np.random.randint(1, 100, size=(3, 4))
b = np.random.randint(1, 9, size=(1, 15))
print(a)
print(b)

[[36 62  9 46]
 [19  5 40 74]
 [54 27 39 20]]
[[6 6 6 3 5 1 3 2 6 1 8 2 6 4 5]]


In [94]:
a = np.array([[5, 10, 21], [11, 23, 18], [22, 19, 35], [96, 22, 26]])
vector_a = np.array(a[3])
sub_a = a[0:4, 2:3] # 0:4: Có các dòng từ 0 đến 3 với tổng là 4 dòng, 2:3 có các cột từ 0 đến 2 tổng là 3 nhưng chỉ lấy từ cột thứ 2 trở đi 
# print(a)
# print(a.size, a.ndim, a.shape)
# # print(a[2], a[3])
# # print(vector_a)
# print(f"In ra sub_a: \n{sub_a}")
# b = a[1:4, 1:3]
# print(f'Ma trận mới: \n{b}')
print(f"Matrix có {a.shape} chiều với kích thước là {a.ndim}. Với kích thước là n:n dòng và m:m cột")
n1 = int(input(f'Nhập vị trí từ dòng: '))
n2 = int(input(f'Nhập vị trí tới dòng: '))
n3 = int(input(f'Nhập vị trí từ dòng: '))
n4 = int(input(f'Nhập vị trí tới dòng: '))
n = int(input(f'Nhập giá trị n: '))
value = a[n1:n2, n3:n4] 
value[0] = n
print(a)


Matrix có (4, 3) chiều với kích thước là 2. Với kích thước là n:n dòng và m:m cột
[[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 22 26]]


In [108]:
a = np.random.randint(10, 20, size=(1, 20-10))
b = a.reshape(2, 5)
print(b)
print(b.shape)

[[13 16 10 11 12]
 [16 16 19 14 16]]
(2, 5)


In [145]:
a = np.array([99, 46, 87, 62, 11, 32])
b = a.reshape(2, 3)
median_a = np.median(a)
array_a = np.sort(a)
array_b = -np.sort(-a)
odd_a = a[a % 2 == 1]
even_a = a[a % 2 == 0]
# if a[4] % 2 == 0:
#     print(f"Phần tử a[4] = {a[4]} là chẵn")
# else:
#     print(f"Phần tử a[4] = {a[4]} là lẻ")
# n1 = int(input("Nhập giá trị cần thay thế: "))
# n2 = np.mean(a)
# if np.any(a == n1):
#     a[a == n1] = n2
#     print(f"Vector sau khi thay thế: {a}")
# else: 
#     print(f"Không tìm thấy {n1} trong vector")
    
# n11 = int(input("Nhập giá trị cần xóa: "))
n11 = 62
if n11 in a:
    a = a[a != n11]
    print(f"Vector mới: {a}")
else:
    print(f"Không tìm thấy giá trị {n11} trong vector")
# print(a)
# print(a.min(), a.max())
# print(array_a)
# print(array_b)
# print(f"Số phần tử chẵn: {odd_a.size}")
# print(np.sort(odd_a))
# print(np.sort(even_a))
# print(f"Trung bình: {a.mean()}, trung vị: {median_a} và tổng: {a.sum()}")

Vector mới: [99 46 87 11 32]


In [177]:
matrix_1 = np.array([[5, 10, 21], [11, 23, 18], [22, 19, 35]])
matrix_2 = np.array([[50, 10, 41], [61, 23, 28], [42, 11, 25]])
matrix_3 = np.array([[96, 22, 26], [87, 56, 23], [90, 75, 32]])
matrix_4 = matrix_2.reshape(3, 3)
vector_5 = matrix_4.flatten()
vector_6 = np.array([matrix_1[0:1, 0:1], matrix_2[0:1, 0:1], matrix_3[0:1, 0:1]]).flatten()
get_two_last_m1 = matrix_1[2:3, 1:3]
print(get_two_last_m1)

mean_m1 = np.mean(matrix_1)
matrix_2[0:1, 0:1] = mean_m1
matrix_3[2:3, 2:3] = -1
vector_5 = np.append(vector_5, 45)
vector_5 = np.insert(vector_5, 0, 99)
# print(matrix_2)
# print(matrix_3.sum())
# print(matrix_3)
# print(matrix_4, matrix_4.shape)
# print(vector_5)
print(vector_6)

[[19 35]]
[ 5 50 96]


In [191]:
ds = [15, 32, 10, 32, 29, 48, 21]
vector_1 = np.array(ds)
vector_2 = np.append(vector_1, 99)
new_matrix_1 = vector_2.reshape(2, 4)
vector_3 = np.insert(vector_1, 1, 55)
new_matrix_2 = vector_3.reshape(4, 2)
print(vector_1)
print(f"Số chiều trong vector là {vector_1.ndim} và số phần tử trong vector là {vector_1.size}")
print(new_matrix_1)
print(f"Vector mới là \n{vector_3} \nMatrix mới là \n{new_matrix_2}")
print(f"Giá trị lẻ là: {vector_1[vector_1 % 2 != 0]}")

[15 32 10 32 29 48 21]
Số chiều trong vector là 1 và số phần tử trong vector là 7
[[15 32 10 32]
 [29 48 21 99]]
Vector mới là 
[15 55 32 10 32 29 48 21] 
Matrix mới là 
[[15 55]
 [32 10]
 [32 29]
 [48 21]]
Giá trị lẻ là: [15 29 21]


In [227]:
# file = open("sinhvien.txt")
# matrix_sv = np.array(file.read())
# matrix_sv = np.insert(matrix_sv, 0, "Stt")
# matrix_sv = np.insert(matrix_sv, 1, "Ten")
# matrix_sv = np.insert(matrix_sv, 2, "Tuoi")
# print(matrix_sv)
# np.savetxt('matrix.txt', matrix_sv, fmt='%d', delimiter=',')

# Open and read the file
file = open("sinhvien.txt")
data = file.readlines()

# Convert data to a NumPy array
matrix_sv = np.array([line.strip().split() for line in data])

# Insert column headers
headers = np.array([["Stt", "HoTen", "Tuoi"]])
matrix_sv = np.vstack((headers, matrix_sv))

# Calculate the average age
ages = matrix_sv[1:, 2].astype(int)  
average_age = np.mean(ages)

print(f"Matrix với tiêu đề: \n{matrix_sv}")
print(f"Tuổi trung bình: {average_age:.2f}")

# Save to txt file with string format
try:
    np.savetxt('matrix.txt', matrix_sv, fmt='%s', delimiter=',')
    print("Lưu thành công")
except Exception as e:
    print(f"Lỗi khi lưu file: {e}")

file.close()

Matrix with headers: 
[['Stt' 'HoTen' 'Tuoi']
 ['1' 'Thanh' '20']
 ['2' 'Tam' '21']
 ['3' 'Binh' '22']
 ['4' 'Chinh' '33']
 ['5' 'Lan' '21']]
Average age: 23.40
Lưu thành công
